# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: init

on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: init mod
      run: |
        set +e
        go fmt main.go
        go mod tidy
        go build -gcflags -help

    - uses: actions/upload-artifact@v4
      with:
        name: src
        path: .
