# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: run

on:
  workflow_dispatch:
    inputs:
      parallelism:
        required: false
        type: string
        default: "700"
      begin_id:
        required: true
        type: string
      end_id:
        required: true
        type: string

jobs:
  collying:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Go run
      run: |
        go mod tidy
        go run -gcflags="-l=4" -ldflags="-s -w" main.go -p ${{inputs.parallelism}} -- ${{inputs.begin_id}} ${{inputs.end_id}}
